### ISSUE TITLE
Add a Feature: Find and Replace

### ISSUE THREAD

**Issue by EmanDev** [marcussacana/EthornellEditor#1]
Is it possible to integrate a Find and Replace function when editing? 

like when editing this kind of script, editing multiple text at once by finding same strings and change them at the same time would be easier when editing
![1231231](https://user-images.githubusercontent.com/25047362/32990254-44f9d826-cd61-11e7-9e1c-007374e37607.png)

**Comment by 0xh3LL0** [comment]
use [sacanawrapper](https://github.com/marcussacana/SacanaWrapper) instead, it has bgi plugin to extract the script which later you can edit with any text editor with find & replace feature...

**Comment by marcussacana** [comment]
how the @0xh3LL0 says, you can use the sacanawrapper and the VNXTLP
And a note:
![https://comfy.moe/xkzkfc.png](https://comfy.moe/xkzkfc.png)
