### ISSUE TITLE
Replace all problem

### ISSUE THREAD

**Issue by Cosetto** [marcussacana/EthornellEditor#2]
Hello sir, how can I turn on/off the replace all function in this in this tool? There're few lines I want to edit. Btw how can I turn to next textbox in this engine? I knew \n cut line but how can I cut it into 2 textboxs.

**Comment by marcussacana** [comment]
I don't get what you mean in the first part of the question, but about split the dialogues:
Simiple, you can't, to that what you will need is a dissassembler of the script, that will allow insert commands in the script that can make the game display a new dialogue, this tool is only to edit the script text, then isn't possible.
You're lucky since the BGI have disassembler tools to their scripts, but that are rare to exist in many engines.

**Comment by Cosetto** [comment]
> I don't get what you mean in the first part of the question, but about split the dialogues:
> Simiple, you can't, to that what you will need is a dissassembler of the script, that will allow insert commands in the script that can make the game display a new dialogue, this tool is only to edit the script text, then isn't possible.
> You're lucky since the BGI have disassembler tools to their scripts, but that are rare to exist in many engines.

Well like "……。" repeats, I changed it to "..."  and  the tool replaced all sentences have it. How can I turn it on/off, because there's line I want to edit. I can't change that line unless I edit the first "……。", but if I change the first "……。", others will change to.

**Comment by marcussacana** [comment]
That is a optimization of the BGI engine, when a line looks like the same to make the script smaller he merge both in one.
The tool as well try do the same, in my tool you can 'disabled it' by removing this part of the code:
https://github.com/marcussacana/EthornellEditor/blob/1dd6033670443286a113fade4620d19167e5585a/EthernelEditor/Main.cs#L198-L202
But that should't cause the problem that you said to be happening; maybe a bug....

**Comment by Cosetto** [comment]
Can you help with it? Right now I'm busy with editing the scripts

**Comment by Cosetto** [comment]
btw I'm bad with coding so please!

**Comment by marcussacana** [comment]
Just remove that lines and build the program.

**Comment by Cosetto** [comment]
But wait your oldest one don't have that right? I actually could use that
